version: '3.7'

services:

  burndown-client:
    container_name: burndown-client
    restart: always
    build:
      "./client"
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
